---
swagger: "2.0"
info:
  description: "test"
  version: "1.0.0"
  title: "chat simples v2"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /broadcast:
    post:
      summary: "popula o chat"
      description: "popula o chat"
      operationId: "broadcast_post"
      parameters:
      - in: "body"
        name: "mensagem"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/msg"
      responses:
        405:
          description: "deu erro, não faço idéia do que seja"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /receive:
    post:
      summary: "recebe mensagem do cliente"
      description: "ficar digitando duas vezes a mesma coisa é ruim"
      operationId: "receive_post"
      parameters:
      - in: "body"
        name: "message"
        description: "a mensagem no corpo da requisição a ser publicada"
        required: true
        schema:
          $ref: "#/definitions/sent_msg"
      responses:
        200:
          description: "mensagem recebida"
        400:
          description: "mensagem não recebida"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /join/{user}:
    get:
      summary: "Junta usuário novo ao servidor"
      description: "Salva o nome no banco de dados do usuário dentro do chat"
      operationId: "join_user_get"
      parameters:
      - name: "user"
        in: "path"
        description: "nome do usuario"
        required: true
        type: "string"
      responses:
        200:
          description: "usuario online"
        400:
          description: "falha de conexao"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /quit/{user}:
    get:
      summary: "desconecta o user do server"
      description: "deleta o nome no banco de dados do usuário dentro do chat"
      operationId: "quit_user_get"
      parameters:
      - name: "user"
        in: "path"
        description: "nome do usuario"
        required: true
        type: "string"
      responses:
        200:
          description: "usuario offline"
        400:
          description: "wtf não rolou desconectar o user"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
securityDefinitions:
  basicAuth:
    type: "basic"
  apiKey:
    description: "jwt cross-token generated by authentication api"
    type: "apiKey"
    name: "X-API-KEY"
    in: "header"
definitions:
  msg:
    type: "string"
  sent_msg:
    type: "string"
